config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  root 'welcome#index'
  resources :claims
  resources :my_claim
  resource :digital, only: [:show], controller: 'static_pages/digital'

  namespace :admin do
    root 'claims#index'
    resources :claims
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/claim.rb
class Claim < ApplicationRecord
  enum claim_type: [:Reciduos, :Alumbrado, :Cloacas, :Agua]
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < Admin::ApplicationController
  before_action :authenticate_admin!
  layout 'admin'
end

app/controllers/admin/claims_controller.rb
class Admin::ClaimsController < Admin::BaseController
  before_action :set_claim, only: [:edit, :update, :show]

  def index
    @claims = Claim.all
  end

  def update
    respond_to do |format|
      if @claim.update(claim_params)
        format.html { redirect_to admin_claims_path, notice: 'Se cambio el estado del reclamo.' }
        format.json { render :show, status: :ok, location: @claim }
      else
        format.html { render :edit }
        format.json { render json: @claim.errors, status: :unprocessable_entity }
      end
    end
  end

  private
  def set_claim
    @claim = Claim.find(params[:id])
  end

  def claim_params
      params.require(:claim).permit(:id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/claims_controller.rb
class ClaimsController < ApplicationController
  before_action :set_claim, only: [:show]

  def new
    @claim = Claim.new
  end

  def create
    @claim = Claim.new(build_create_params)
    respond_to do |format|
      if @claim.save
        format.html { redirect_to claim_path(@claim), notice: 'Reclamo creado correctamente.' }
        format.json { render :show, status: :created, location: @claim }
      else
        format.html { render :new }
        format.json { render json: @claim.errors, status: :unprocessable_entity }
      end
    end
  end

  private
  def claim_params
    params.require(:claim)
      .permit(:claim_type ,:body)
  end

    def set_claim
      @claim = Claim.find(params[:id])
    end

  def build_create_params
    claim_params.merge(state: 0, claim_code: generate_claim_code)
  end

  def generate_claim_code
    code = SecureRandom.hex(5)
      if Claim.where(claim_code: code).any?
        code = SecureRandom.hex
      end
    code
  end
end

app/controllers/my_claim_controller.rb
class MyClaimController < ApplicationController

  def new
  end

  def show
    @my_claim = Claim.find(params[:id])
  end

  def create
    @my_claim = Claim.find_by(claim_code: params[:claim_code])
    respond_to do |format|
      unless @my_claim.nil?
        format.html { redirect_to my_claim_path(@my_claim), notice: 'Se encontro su reclamo' }
        format.json { render :show, status: :created, location: @my_claim }
      else
        format.html { render :new }
        format.json { render json: @my_claim.errors, status: :unprocessable_entity }
      end
    end
  end

  private
end

app/controllers/static_pages/digital_controller.rb
class StaticPages::DigitalController < ApplicationController
  def show
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/claim_type_helper.rb
module ClaimTypeHelper
  def claim_types_for_select
    Claim.claim_types.keys
  end
end

app/views/admin/claims/index.html.erb
<% if notice %>
 <div class="alert alert-success" role="alert">
   <button type="button" class="close" data-dismiss="alert" aria-label="Close">
     <span aria-hidden="true">&times;</span>
   </button>
   <%= notice %>
 </div>
<% end %>

<h1>Reclamos</h1>

<table>
  <thead>
    <tr>
      <th>Tipo</th>
      <th>reclamo</th>
      <th>codigo</th>
      <th>estado</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @claims.each do |claim| %>
      <tr>
        <td><%= claim.claim_type %></td>
        <td><%= claim.body %></td>
        <td><%= claim.claim_code %></td>
        <td><%= claim.state %></td>
        <td><%= link_to 'show', admin_claim_path(claim) %></td>
        <td><%= link_to 'edit', edit_admin_claim_path(claim) %></td>
        <td><%= link_to 'delete', admin_claim_path(claim), method: :delete, data: { confirm: '¿Estás seguro?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'nuevo', new_admin_claim_path %>

app/views/claims/_form.html.erb
<section class="page-title page-title-4 image-bg overlay">
  <div class="background-image-holder fadeIn">
    <%= image_tag("reclamos.jpg") %>
  </div>
  <div class="container">
    <div class="row">
      <div class="col-md-6">
        <h2 class="uppercase mb8">Reclamos</h2>
        <p class="lead mb0">Hace tu reclamo de forma</p>
        <p class="lead mb0">rapida y facil</p>
      </div>
    </div>
    <!--end of row-->
  </div>
  <!--end of container-->
</section>

<section>
  <div class="container">
  <% if @claim.errors.any? %>
    <div class="alert alert-danger" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
      <h2><%= pluralize(@claim.errors.count, "error") %> prohibió que este @claimo se guarde:</h2>

      <ul>
      <% @claim.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <div class="row">
      <div class="col-sm-6 col-sm-offset-3">
        <%= form_for(@claim) do |form| %>
          <div class="form-group">
            <%= form.label :reclamo_sobre %>
            <%= form.select :claim_type, claim_types_for_select, { include_blank: "Seleccionar tipo de reclamo" }, required: true %>
          </div>

          <div class="form-group">
            <%= form.label :escribi_tu_reclamo %>
            <%= form.text_area :body, class: 'form-control', required: true, size: "20x10" %>
          </div>

          <div class="actions">
            <%= form.submit 'Aceptar' %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/claims/new.html.erb
<%= render 'form' %>

app/views/claims/show.html.erb
<% if notice %>
 <div class="alert alert-success" role="alert">
   <button type="button" class="close" data-dismiss="alert" aria-label="Close">
     <span aria-hidden="true">&times;</span>
   </button>
   <%= notice %>
 </div>
<% end %>

<section class="page-title page-title-4 image-bg overlay">
  <div class="background-image-holder fadeIn">
    <%= image_tag("reclamos.jpg") %>
  </div>
  <div class="container">
    <div class="row">
      <div class="col-md-6">
        <h2 class="uppercase mb8">Reclamos</h2>
        <p class="lead mb0">Hace tu reclamo de forma</p>
        <p class="lead mb0">rapida y facil</p>
      </div>
    </div>
    <!--end of row-->
  </div>
  <!--end of container-->
</section>

<section class="fullscreen" style="height: 575px;">
    <div class="container v-align-transform">
        <div class="row">
            <div class="col-sm-10 col-sm-offset-1">
                <div class="feature text-center">
                    <i class="ti-check-box icon icon-lg mb24 mb-xs-0"></i>
                    <h1 class="large">Tu reclamo fue creado!</h1>
                    <h4 class="large">Numero de reclamo: <%= @claim.claim_code %></h4>
                    <h5 class="large">Anota este numero, te servira para hacer el seguimiento de tu reclamo.</h5>
                    <p class="mb40 mb-xs-24">Muchas gracias por dejarnos tus reclamos, juntos haremos un Yerba Buena mejor.
                    </p>
                </div>
            </div>
        </div>
    </div>
    <!--end of container-->
</section>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>admin</title>
    <%= csrf_meta_tags %>

    <meta content="width=device-width, initial-scale=1, maximum-scale=1" name="viewport">
    <%= stylesheet_link_tag    'admin', media: 'all' %>
    <%= javascript_include_tag 'admin' %>
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,300,600,400italic,700,800' rel='stylesheet' type='text/css' >
    <link   href='https://fonts.googleapis.com/css?family=Raleway:300,200,100' rel='stylesheet' type='text/css'>
  </head>

  <body>
    <div id="cl-wrapper">
      <%= render 'shared/admin/sidebar' %>

      <div id="pcont" class="container-fluid">
        <%= render 'shared/admin/navbar' %>

        <div class="cl-mcont">
          <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sanjose</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/nav-bar' %>
    <%= yield %>
    <%= render 'shared/footer' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </body>
</html>

app/views/my_claim/_form.html.erb
<section class="page-title page-title-4 image-bg overlay">
  <div class="background-image-holder fadeIn">
    <%= image_tag("reclamos.jpg") %>
  </div>
  <div class="container">
    <div class="row">
      <div class="col-md-6">
        <h2 class="uppercase mb8">Reclamos</h2>
        <p class="lead mb0">Hace tu reclamo de forma</p>
        <p class="lead mb0">rapida y facil</p>
      </div>
    </div>
    <!--end of row-->
  </div>
  <!--end of container-->
</section>

<section class="fullscreen" style="height: 575px;">
    <div class="container v-align-transform">
        <div class="row">
            <div class="col-sm-10 col-sm-offset-1">
                <div class="feature text-center">
                    <h1 class="large">Revisa tu reclamo!</h1>
                    <h4 class="large">Numero de reclamo: </h4>
                    <%= form_tag({controller: "my_claim", action: "create"}, method: "post") do %>
                      <div class="form-group">
                        <%= text_field_tag(:claim_code) %>
                      </div>

                      <div class="actions">
                        <%= submit_tag("Aceptar") %>
                      </div>
                    <% end %>
                </div>
            </div>
        </div>
    </div>
    <!--end of container-->
</section>

app/views/my_claim/index.html.erb
<section class="image-square left">
    <div class="col-md-6 image">
        <div class="background-image-holder fadeIn" style="background: url(&quot;img/cover11.jpg&quot;);">
            <%= image_tag("cover11.jpg", class: 'background-image') %>
        </div>
    </div>
    <div class="col-md-6 col-md-offset-1 content">
        <h3>Hacer un reclamo</h3>
        <p class="mb0">
            Ahora podes hacer tus reclamos de una manera mas facil y rapida. Luego podras hacer el seguimiento del mismo.
        </p>
        <br>
        <br>
        <%= link_to "HACER UN RECLAMO", new_claim_path, class: 'btn btn-lg' %>
    </div>
</section>

<section class="image-square right">
    <div class="col-md-6 image">
        <div class="background-image-holder fadeIn">
            <%= image_tag("reclamos.jpg", class: 'background-image') %>
        </div>
    </div>
    <div class="col-md-6 content">
        <h3>Seguimiento de un reclamo</h3>
        <p class="mb0">
            Desde aqui podras ver si tu reclamo fue contestado y el estado del mismo.
        </p>
        <br>
        <br>
        <%= link_to "VER UN RECLAMO", new_my_claim_path, class: 'btn btn-lg' %>
    </div>
</section>

app/views/my_claim/new.html.erb
<%= render 'form' %>

app/views/my_claim/show.html.erb
<section class="pt180 pb180 pt-xs-80 pb-xs-80">
  <div class="container">
      <div class="row">
          <div class="col-md-8 col-md-offset-2 col-sm-10 col-sm-offset-1 text-center">
              <h3 class="mb40 mb-xs-32">Tipo de Reclamo: <%= @my_claim.claim_type %></h3>
              <p class="lead mb0">
                 <%= @my_claim.body %>
              </p>
              <br>
              <h3 class="mb40 mb-xs-32"> Respuesta: </h3>
              <% unless @my_claim.response.nil? %>
                <p>
                   <%= @my_claim.response %>
                </p>
              <% else %>
                <p>
                  Aun no se respondio este reclamo
                </p>
              <% end %>
          </div>
      </div>
      <!--end of row-->
  </div>
  <!--end of container-->
</section>

app/views/shared/_footer.html.erb
       <footer class="bg-primary pt96 pb96 pt-xs-48 pb-xs-48">
          <div class="container">
            <div class="row mb64 mb-xs-32">
              <div class="col-md-5 text-right text-left-xs">
                <h2 class="uppercase bold italic">Yerba Buena<br> Tu ciudad<br> tu jardín</h2>
              </div>
              <div class="col-md-2 hidden-sm hidden-xs text-center pt48">
                <%= image_tag("yb.png", class: 'display-block') %>
              </div>
              <div class="col-md-5 col-sm-6">
                <p class="lead">
                  Comunicate con nosotros por los siguientes medios<br class="hidden-sm">
                  Trataremos de contestarte a la brevedad.
                </p>
                <h4 class="mb8">Tel: 3815456789</h4>
                <h4 class="mb8">Email: delegacion@yerbabuena.com</h4>
                <h4 class="mb0"><i class="ti-twitter-alt"></i> @delegacionYb</h4>
              </div>
            </div>
            <div class="row">
              <div class="col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2 text-center">
                <p class="fade-1-4">Wavelabs © 2018
                </p><ul class="list-inline social-list mb0">
                  <li><a href="#"><i class="icon icon-xs ti-twitter-alt"></i></a></li>
                  <li><a href="#"><i class="icon icon-xs ti-facebook"></i></a></li>
                  <li><a href="#"><i class="icon icon-xs ti-instagram"></i></a></li>
                </ul>
              </div>
            </div>
          </div>
      </footer>

app/views/shared/_nav-bar.html.erb
    <div class="nav-container">    
      <nav>
          <div class="nav-bar">
              <div class="module left">
                <%= link_to root_path do %>
                  <%= image_tag 'logo-light', class: "logo logo-light" %>
                  <%= image_tag 'yerbabuena', class: "logo logo-dark" %>
                <% end %>
              </div>
              <div class="module widget-handle mobile-toggle right visible-sm visible-xs">
                  <i class="ti-menu"></i>
              </div>
              <div class="module-group right">
                  <div class="module left">
                      <ul class="menu">
                          <li>
                              <a href="#">Inicio</a>
                          </li>
                          <li>
                              <a href="#">¿Qué es Punto Digital?</a>
                          </li>
                          <li>
                              <a href="#">Areas</a>
                          </li>
                      </ul>
                  </div>
                  
              </div>
              
          </div>
      </nav>
    </div>

app/views/shared/admin/_navbar.html.erb
<div id="head-nav" class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-collapse">
      <ul class="nav navbar-nav navbar-right user-nav">
        <li class="dropdown profile_menu">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            <span><%= current_admin.email %></span>
            <b class="caret"></b>
          </a>
          <ul class="dropdown-menu">
            <li>
              <%= link_to 'Salir', destroy_admin_session_path, method: :delete %>
            </li>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</div>

app/views/shared/admin/_sidebar.html.erb
<div class="cl-sidebar">
  <div class="cl-toggle">
    <i class="fa fa-bars"></i>
  </div>
  <div class="cl-navblock">
    <div class="menu-space">
      <div class="content">
        <%= link_to admin_root_path do %>
          <div class="sidebar-logo">
            <div class="logo text-center">
              <div class="row">
                <div class="col-lg-12 hidden-sm hidden-xs">
                  <%= image_tag 'logo-light.png', class: "logo-cms" %>
                </div>
                <div class="hidden-lg hidden-md visible-xs-12">
                  <%= image_tag 'yb.png', class: "logo-mini"%>
                </div>
              </div>
            </div>
          </div>
        <% end %>
        <div class="side-user">
          <div class="info">
            <p>
              <i class="fa fa-user"></i>
              Panel de Administrador
            </p>
          </div>
        </div>
        <ul class="cl-vnavigation">
          <li>
            <a href="#">
              <i class="fa fa-folder"></i>
              <span>Reclamos</span>
            </a>
            <ul class="sub-menu">
              <li class="">
                <%= link_to "Lista de Reclamos", admin_claims_path %>
              </li>
            </ul>
          </li>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/static_pages/digital/show.html.erb
<div class="main-container">
          
      <section class="cover fullscreen image-slider slider-all-controls controls-inside parallax">
            <ul class="slides">
                <li class="overlay image-bg">
                    <div class="background-image-holder">
                        <%= image_tag("back.png", class: 'background-image') %>
                    </div>
                    <div class="container v-align-transform">
                        <div class="row">
                            <div class="col-md-6 col-sm-8">
                                <h1 class="mb40 mb-xs-16 large">Permanece conectado<br></h1>
                                <h6 class="uppercase mb16">Punto digital yerba buena</h6>
                                <p class="lead mb40">Te invitamos a aprender, divertirte y crecer en comunidad</p>
                                
                            </div>
                        </div>
                        
                    </div>
                    
                </li>
            </ul>
        </section>
        <section class="image-bg overlay parallax">
            <div class="background-image-holder">
                <%= image_tag("punto-digital-de-yerba-buena.jpeg", class: 'background-image') %>
            </div>
            <div class="container">
                <div class="row">
                    <div class="col-sm-12 text-center">
                        <h2 class="mb16">!El Punto Digital está abierto para vos!</h2>
                        <p class="lead mb64">Te invitamos a conocer las distintas actividades que están disponibles para vos.</p>
                    </div>
                </div>
                
                <div class="row">
                    <div class="col-sm-4">
                        <div class="feature feature-1 boxed">
                            <div class="text-center">
                                <i class="ti-package icon"></i>
                                <h5 class="uppercase">¿Qué es punto digital?</h5>
                            </div>
                            <p>Los Puntos Digitales forman parte de las políticas de inclusión tecnológica desarrolladas por el ministerio de modernización, a través del Plan País Digital, para que vos, tus vecinos y familiares puedan estar cada día mas conectados</p>
                        </div>
                        
                    </div>
                    <div class="col-sm-4">
                        <div class="feature feature-1 boxed">
                            <div class="text-center">
                                <i class="ti-infinite icon"></i>
                                <h5 class="uppercase">formación continua</h5>
                            </div>
                            <p>Punto Digital tiene como objetivo desarrollar actividades de capacitación tecnológica para todas la edades. Este sector cuenta con computadoras con acceso libre a Internet disponible para la comunidad y una plataforma Online con mas de 200 cursos virtuales&nbsp;</p>
                        </div>
                        
                    </div>
                    <div class="col-sm-4">
                        <div class="feature feature-1 boxed">
                            <div class="text-center">
                                <i class="ti-heart icon"></i>
                                <h5 class="uppercase">anses</h5>
                            </div>
                            <p>
                                Contamos con una oficina de ANSES&nbsp; para asistir a los vecinos&nbsp; y guiarlos en los diversos tramites que tienen que realizar</p>
                        </div>
                        
                    </div>
                </div>
                
            </div>
            
        </section><section class="pb64 pb-xs-40">
            <div class="container">
                <div class="row">
                    <div class="col-sm-4">
                        <div class="feature feature-2 filled text-center">
                            <div class="text-center">
                                <i class="fa fa-tv fa-3x"></i>
                                <h5 class="uppercase">APRENDIZAJE</h5>
                            </div>
                            <p>En el área de aprendizaje se desarrollan actividades de capacitación tecnológica para todas las edades.</p>
                        </div>
                        
                    </div>
                    <div class="col-sm-4">
                        <div class="feature feature-2 filled text-center">
                            <div class="text-center">
                                <i class="fa fa-video-camera fa-3x"></i>
                                <h5 class="uppercase">CINE</h5>
                            </div>
                            <p>
                                El espacio de Cine se utiliza para compartir grandes eventos comunitarios, como transmisiones deportivas, celebraciones patrias y transmitir actividades culturales en vivo.</p>
                        </div>
                        
                    </div>
                    <div class="col-sm-4">
                        <div class="feature feature-2 filled text-center">
                            <div class="text-center">
                                <i class="fa fa-gamepad fa-3x"></i>
                                <h5 class="uppercase">ENTRETENIMIENTO</h5>
                            </div>
                            <p>
                                Esta área está equipada con videoconsolas de juego con mandos inalámbricos de última generación, para que grandes y chicos aprendan y se diviertan.</p>
                        </div>
                        
                    </div>
                </div>
                
            </div>
    </div>

app/views/welcome/index.html.erb
    <div class="main-container">
          
      <section class="cover fullscreen image-slider slider-all-controls controls-inside parallax">
            <ul class="slides">
                <li class="overlay image-bg">
                    <div class="background-image-holder">
                        <%= image_tag("SANJOSE1.jpg", class: 'background-image') %>
                    </div>                    
                </li>
            </ul>
        </section>

      <section class="cover fullscreen image-slider slider-all-controls controls-inside parallax">
            <ul class="slides">
                <li class="overlay image-bg">
                    <div class="background-image-holder">
                        <%= image_tag("anses.png", class: 'background-image') %>
                    </div>
                    <div class="container v-align-transform">
                        <div class="row">
                            <div class="col-md-6 col-sm-8">
                                <h1 class="mb40 mb-xs-16 large">PUNTO DE CONTACTO ANSES<br></h1>
                                <h6 class="uppercase mb16">Mas cerca de vos.</h6>
                                <p class="lead mb40">Lunes a viernes de 8 a 13</p>
                                
                            </div>
                        </div>
                        
                    </div>
                    
                </li>
            </ul>
        </section>

        <section class="cover fullscreen image-slider slider-all-controls controls-inside parallax">
                <ul class="slides">
                    <li class="overlay image-bg">
                        <div class="background-image-holder">
                            <%= image_tag("back.png", class: 'background-image') %>
                        </div>
                        <div class="container v-align-transform">
                            <div class="row">
                                <div class="col-md-6 col-sm-8">
                                    <h1 class="mb40 mb-xs-16 large">Permanece conectado<br></h1>
                                    <h6 class="uppercase mb16">Punto digital yerba buena</h6>
                                    <p class="lead mb40">Te invitamos a aprender, divertirte y crecer en comunidad</p>
                                    <%= link_to "Ver mas", digital_path, class: 'btn btn-lg' %>
                                    
                                </div>
                            </div>
                            
                        </div>
                        
                    </li>
                </ul>
        </section>

        <section class="cover fullscreen image-slider slider-all-controls controls-inside parallax">
                <ul class="slides">
                    <li class="overlay image-bg">
                        <div class="background-image-holder">
                            <%= image_tag("reclamos.jpg", class: 'background-image') %>
                        </div>
                        <div class="container v-align-transform">
                            <div class="row">
                                <div class="col-md-6 col-sm-8">
                                    <h1 class="mb40 mb-xs-16 large">Hacer un reclamo<br></h1>
                                    <h6 class="uppercase mb16">Hace tu reclamo</h6>
                                    <p class="lead mb40">Juntos haremos un San Jose mejor</p>
                                    <%= link_to "HACER UN RECLAMO", my_claim_index_path, class: 'btn btn-lg' %>
                                </div>
                            </div>
                            
                        </div>
                        
                    </li>
                </ul>
        </section>

        <section class="cover fullscreen image-slider slider-all-controls controls-inside parallax">
            <ul class="slides">
                <li class="overlay image-bg">
                    <div class="background-image-holder">
                        <%= image_tag("camion.jpg", class: 'background-image') %>
                    </div>
                    <div class="container v-align-transform">
                        <div class="row">
                            <div class="col-md-6 col-sm-8">
                                <h1 class="mb40 mb-xs-16 large">RECOLECCION DE RECIDUOS<br></h1>
                                <h6 class="uppercase mb16">Recolección de reciduos verdes</h6>
                            </div>
                        </div>
                        
                    </div>
                    
                </li>
            </ul>
        </section>

        <section class="image-square right">
            <div class="col-md-6 p0 image">
                <div class="map-holder background-image-holder">
                    <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3561.3987023996347!2d-65.26117388521686!3d-26.795430694776048!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x94225d16fe57d199%3A0x14041e6cffec0aa1!2sJuan+B.+Alberti+75%2C+Yerba+Buena%2C+Tucum%C3%A1n!5e0!3m2!1ses-419!2sar!4v1533825365383" width="600" height="450" frameborder="0" style="border:0" allowfullscreen></iframe>
                </div>
            </div>
            <div class="col-md-6 content">
                <form class="form-email" data-success="Thanks for your submission, we will be in touch shortly." data-error="Please fill all fields correctly.">
                    <h6 class="uppercase text-center">Enviar mensaje</h6>
                    <input type="text" class="validate-required" name="name" placeholder="Nombre">
                    <input type="text" class="validate-required validate-email" name="email" placeholder="Correo Electronico">
                    <textarea class="validate-required" name="message" rows="4" placeholder="Mensaje"></textarea>
                    <button type="submit">enviar</button>
                </form>
            </div>
        </section>
    </div>